export const NEXT_CONFIG_MJS = `import createMDX from '@next/mdx'
import rehypePrettyCode from 'rehype-pretty-code'
import rehypeSlug from 'rehype-slug'
import remarkGfm from 'remark-gfm'
import { visit } from 'unist-util-visit'

/** @type {import('next').NextConfig} */
const nextConfig = {
  pageExtensions: ['js', 'jsx', 'mdx', 'ts', 'tsx'],
}

const withMDX = createMDX({
  options: {
    remarkPlugins: [remarkGfm],
    rehypePlugins: [
      () => (tree) => {
        visit(tree, (node) => {
          if (node?.type === 'element' && node?.tagName === 'pre') {
            const [codeElement] = node.children
            if (codeElement.tagName !== 'code') return
            node.raw = codeElement.children[0]?.value
          }
        })
      },
      [
        rehypePrettyCode,
        {
          keepBackground: false,
        },
      ],
      rehypeSlug,
      () => (tree) => {
        visit(tree, (node) => {
          if (node?.type === 'element' && node?.tagName === 'figure') {
            if ((!'data-rehype-pretty-code-figure') in node.properties) {
              return
            }
            const preElement = node.children.at(-1)
            if (preElement.tagName !== 'pre') return
            preElement.properties = {
              ...preElement.properties,
              raw: node.raw,
            }
          }
        })
      },
    ],
  },
})

export default withMDX(nextConfig)
`

export const MDX_COMPONENT_TSX = `import type { MDXComponents } from 'mdx/types'

export function useMDXComponents(components: MDXComponents): MDXComponents {
  return {
    ...components,
  }
}
`

export const RDOCS_SIDEBAR_YAML = `- title: Getting Started
- title: Introduction
  href: /docs
- title: Installation
  href: /docs/installation
`

export const DEMO_LAYOUT_TSX = `import { sidebarConfig } from './sidebar'
import { ReadraveSidebar } from '@/components/readrave/sidebar'

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <div className="mx-auto max-w-screen-xl px-5 pb-20 md:grid md:grid-cols-[200px_minmax(0,1fr)] md:gap-6 lg:grid-cols-[240px_minmax(0,1fr)] lg:px-7">
      <ReadraveSidebar sidebarConfig={sidebarConfig} />
      <main className="pt-6">
        <article className="prose max-w-none dark:prose-invert">
          {children}
        </article>
      </main>
    </div>
  )
}
`

export const DEMO_MDX = `Automatically generated by [Readrave](https://readrave.com)
`

export const DEMO_SIDEBAR = `'use client'

import { ScrollArea } from '@/components/ui/scroll-area'
import { cn } from '@/lib/utils'
import Link from 'next/link'
import { usePathname } from 'next/navigation'

export const ReadraveSidebar = ({
  sidebarConfig,
}: {
  sidebarConfig: { title: string; href?: string; css?: any }[]
}) => {
  const pathname = usePathname()

  return (
    <aside className="z-6 top-14 hidden h-[calc(100dvh-3.5rem)] md:sticky md:block">
      <ScrollArea className="h-full py-6">
        <nav className="flex flex-col space-y-2.5 text-sm text-foreground/50">
          {sidebarConfig.map((item, i) => (
            <span key={i}>
              {item.href ? (
                <Link
                  href={item.href}
                  className={cn(
                    'font-foreground/50 hover:text-primary hover:underline',
                    pathname === item.href && 'font-medium text-primary',
                  )}
                  style={item.css}
                >
                  {item.title}
                </Link>
              ) : (
                <p
                  className="font-semibold text-foreground/75 select-none"
                  style={item.css}
                >
                  {item.title}
                </p>
              )}
            </span>
          ))}
        </nav>
      </ScrollArea>
    </aside>
  )
}
`
